#打印jpa的sql和参数
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zlijuan
    username: root
    password: zengleping
    driverClassName: com.mysql.jdbc.Driver
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: true
    show-sql: true
    format_sql: true
    
  freemarker:
    request-context-attribute: request
    
  redis:
    host: localhost  
    port: 6379

server:
  servlet-path: /
  session:
    timeout: 7200
